spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: username
    url: url
    password: pw

  profiles:
    include: 
      - sec
    active: local

mybatis:
  type-aliases-package: com.hifive.testapp
  mapper-locations: classpath:mapper/**/*.xml

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true